config/routes.rb
Empfaenger::Application.routes.draw do
  root 'home#index'
  resources :feeds, only: [:new, :create]
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def new

  end
  def create
    feed = Feed.new(feed_params)
    if feed.save
      redirect_to "/"
     else
      render nothing: true
    end
  end
  private
  def feed_params
    params.require(:feed).permit(:address)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def create
    feed = Feed.new(feed_params)
    if feed.save
      redirect_to "/"
     else
      render nothing: true
    end
  end
  private
  
  def feed_params
    params.require(:feed).permit(:address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/feeds/new.html.erb
<%= form_for @feed do |f| %>
  <div class="form-group">
    <%= f.text_field :address, :class => "form-control", :placeholder => "Create a new feed"%>
  </div>
  <%= f.submit %>
<% end %>
<%= form_tag("/new_feed", method: "post", role: "form", class: "form-inline") do %>
  <div class="form-group">
    <%= text_field_tag(:feed, nil, :class => "form-control", :placeholder => "Create a new feed") %>
  </div>
  <%= submit_tag("Create", :class => "btn btn-default") %>
<% end %>

app/views/home/index.html.erb
  <script id="item-template" type="text/x-jquery-tmpl">
    <div class="podcast-list-item">
      <a href="#" class="thumbnail">
        <img data-src="${image}" alt="${title}" src="${image}">
      </a>
    </div>
  </script>
  <script id="podcast-detail-template" type="text/x-jquery-tmpl">
    <div id="podcast-details">
      <div class="page-header">
        <h1>${title} <small>by ${author}</small></h1>
      </div>
      <div class="row">
        <div class="col-md-2">
          <ul class="list-unstyled">
            {{each episodes}}
              <li>
                <div class="row" style="margin-top:5px;margin-bottom:5px;">
                  <div class="col-md-10">
                    <a href="#" class="podcast-title pull-left">${$value.get("title")}</a>
                  </div>
                  <div class="col-md-2">
                    <button type="button" class="btn btn-primary btn-xs pull-right">Play</button>                  
                  </div>
                </div>
              </li>
            {{/each}}
          </ul>
        </div>
        <div class="col-md-6">
          <h3 id="podcast-episode-title"></h3>
          <p id="podcast-episode-description"></p>
          <button type="button" class="btn btn-success">Play episode</button>
        </div>
        <div class="col-md-4">
          <a href="#" class="thumbnail">
            <img src="" id="podcast-episode-thumbnail">
          </a>
        </div>
      </div>
    </div>
  </script>
<div id="header" class="row">
  <div class="col-md-4">
    <p id="header-text">
      Empfaenger
    </p>
  </div>
  <div class="col-md-4">
    <div id="add-feed-form">
      <%= button_to "New feed", new_feed_path, :method => "get", :class => "btn btn-default" %>
    </div>
  </div>
</div>
<div class="row">
  <div id="feed-list" class="col-md-2">
  </div>
  <div class="col-md-10" id="feed-content">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Empfaenger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>